### ISSUE TITLE
Final release 1.0.0

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgerytutorial02#39]
I am opening this issue to prepare the final release 1.0.0 of /scikit-surgerytutorial02. 

* [x] build the docs https://github.com/SciKit-Surgery/scikit-surgerytutorial02/issues/37
* [x] add label priorities to issues (p0-critical, p1-high, p2-medium, p3-low)
* [x] Update package requirements (e.g.`scikit-surgeryvtk==2.0.1`) and test tutorial instructions 
* [x] adds useful commands for debugging https://github.com/SciKit-Surgery/scikit-surgerytutorial02/issues/35
* [x] Solves "Change PYPI_PASS to PYPI token" https://github.com/SciKit-Surgery/scikit-surgerytutorial02/issues/21
* [x] Change branch in https://readthedocs.org/dashboard/scikit-surgerytutorial02/advanced/ to test docs
* [x] address https://github.com/SciKit-Surgery/scikit-surgerytutorial02/issues/36
* [x] Change default branch in https://readthedocs.org/dashboard/scikit-surgerytutorial02/advanced/ It changes automatically after merging feature branch to main
* [x] Create tag 
```
git tag -a 'v1.0.0' -m "Release version v1.0.0"
git push origin v1.0.0
```
* [x] Add release summary using tag https://github.com/SciKit-Surgery/scikit-surgerytutorial02/releases/tag/v1.0.0
